services:

  postgres:
    image: postgres:15
    container_name: cicd-db
    restart: always
    environment:
      POSTGRES_USER: cicd_user
      POSTGRES_PASSWORD: cicd_pass
      POSTGRES_DB: cicd_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: cicd-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:8.12.0
    container_name: cicd-logstash
    restart: always
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:latest
    container_name: cicd-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  es_data:
  grafana_data: