# orchestrator/github_client.py
# Handles all GitHub API interactions — fetching logs, opening PRs, retrying runs

import requests
import os
from github import Github
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28"
}


def get_logs_from_github(repo: str, run_id: int) -> str:
    """Fetch raw logs for a failed workflow run."""
    import zipfile, io
    url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/logs"
    response = requests.get(url, headers=HEADERS, allow_redirects=True)

    if response.status_code != 200:
        return f"ERROR: Could not fetch logs. Status: {response.status_code}"

    zip_bytes = io.BytesIO(response.content)
    all_logs = []
    with zipfile.ZipFile(zip_bytes) as z:
        for filename in z.namelist():
            if filename.endswith('.txt'):
                with z.open(filename) as f:
                    content = f.read().decode('utf-8', errors='replace')
                    all_logs.append(f"=== {filename} ===\n{content}")

    return '\n\n'.join(all_logs)


def retrigger_pipeline(repo: str, run_id: int) -> bool:
    """Re-trigger a failed workflow run."""
    url = f"https://api.github.com/repos/{repo}/actions/runs/{run_id}/rerun"
    response = requests.post(url, headers=HEADERS)
    return response.status_code == 201


def open_fix_pr(repo: str, filename: str, old_content: str, new_content: str, fix_description: str) -> str:
    """Open a PR with the suggested fix."""
    try:
        g = Github(GITHUB_TOKEN)
        gh_repo = g.get_repo(repo)

        # Create a new branch for the fix
        base_branch = gh_repo.get_branch("master")
        fix_branch = f"auto-fix/{filename.replace('/', '-')}-{base_branch.commit.sha[:7]}"

        gh_repo.create_git_ref(
            ref=f"refs/heads/{fix_branch}",
            sha=base_branch.commit.sha
        )

        # Update the file on the new branch
        file = gh_repo.get_contents(filename, ref="master")
        gh_repo.update_file(
            path=filename,
            message=f"fix: {fix_description}",
            content=new_content,
            sha=file.sha,
            branch=fix_branch
        )

        # Open the PR
        pr = gh_repo.create_pull(
            title=f"[Auto-fix] {fix_description}",
            body=f"This PR was automatically generated by the AI-Powered CI/CD Orchestrator.\n\n**Fix:** {fix_description}",
            head=fix_branch,
            base="master"
        )

        return pr.html_url

    except Exception as e:
        return f"ERROR opening PR: {str(e)}"
