{
 "title": "CI/CD Pipeline Metrics",
 "time": { "from": "2026-03-01T13:24:03.880Z", "to": "2026-03-31T13:24:03.880Z" },
 "panels": [
  {
   "title": "Pipeline Failures Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "cicd_db",
     "rawSql": "SELECT\r\ncreated_at as time,\r\n1 as value,\r\nfailure_type as metric\r\nFROM pipeline_events\r\nORDER BY created_at;"
    }
   ]
  },
  {
   "title": "Auto-Fix Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cicd_db",
     "rawSql": "SELECT ROUND(COUNT(*) FILTER (WHERE fix_successful = true) * 100.0 / NULLIF(COUNT(*),0), 1) as value FROM pipeline_events;"
    }
   ]
  },
  {
   "title": "Failure types ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "cicd_db",
     "rawSql": "SELECT failure_type, COUNT(*) as count \r\nFROM pipeline_events \r\nGROUP BY failure_type \r\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Total Failures Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cicd_db",
     "rawSql": "SELECT COUNT(*) as value FROM pipeline_events;"
    }
   ]
  }
 ]
}